[package]
name = "listMaker217"
version = "0.1.1"
edition = "2021"


[dependencies]
rand = "0.8.4"
rayon = "1.5"
chrono = "0.4"
term_size = "0.3" # Check for the latest version on crates.io
colored = "2.0"  # or the latest version
winapi = { version = "0.3", features = ["wincon"] }
